### ISSUE TITLE
drupal in a shared hosting

### ISSUE THREAD

**Issue by slamonega** [markaspot/mark-a-spot#82]
Hi, I have a drupal installarion in my shared hosting, how can I use mark a spot in it?  which files and configurations are need it?
regards,
sebas

**Comment by markaspot** [comment]
Hey, I am sorry but due to current time constraints, I'm unable to provide detailed support for specific Drupal configurations. I recommend checking the Drupal community forums or the Drupal documentation for guidance on managing your installation. These resources often have detailed instructions and can be a great help for specific issues like the one you're encountering.

I'm closing this for housekeeping purposes.
